# Nome do workflow que será exibido na aba 'Actions' do GitHub
name: CI/CD Docker e Pull Request

# Define o gatilho (trigger) para o workflow
on:
  # O workflow será executado a cada novo 'push'
  push:
    # Apenas quando o push for para o branch 'main'
    branches:
      - main

# Define os 'jobs' (tarefas) que o workflow irá executar
jobs:
  # Nome do job: 'build-and-deploy'
  build-and-deploy:
    # O job irá rodar em um ambiente (máquina virtual) com Ubuntu na versão mais recente
    runs-on: ubuntu-latest
    
    # Define a sequência de 'steps' (passos) que o job irá executar
    steps:
      # --- Passo 1: Checkout do Código da Aplicação ---
      - name: Checkout do Código da Aplicação
        uses: actions/checkout@v4
      
      # --- Passo 2: Login no Docker Hub ---
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # --- Passo 3: Construir e Publicar a Imagem Docker ---
      - name: Construir e Publicar a Imagem Docker
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:latest,${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}

      # --- Passo 4: Checkout do Repositório de Manifestos ---
      - name: Checkout do Repositório de Manifestos
        uses: actions/checkout@v4
        with:
          repository: 'LuanLindolfo/hello-manifests'
          path: manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # --- Passo 5: Atualizar a Tag da Imagem no Arquivo de Manifestos ---
      - name: Atualizar a Tag da Imagem no Arquivo de Manifestos
        run: |
          TAG_NAME=${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}
          # Agora o comando procura por 'deployment.yaml' no diretório atual
          sed -i "s|image: .*|image: ${TAG_NAME}|g" deployment.yaml
        # **AQUI ESTÁ A PRIMEIRA CORREÇÃO:** Muda o diretório de trabalho para a pasta 'manifests'
        working-directory: ./manifests

      # --- Passo 6: Commit e Push das Alterações ---
      - name: Commit e Push das Alterações
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add deployment.yaml
          git commit -m "Update hello-app image to ${{ github.sha }}"
          git push
        # **AQUI ESTÁ A SEGUNDA CORREÇÃO:** Muda o diretório de trabalho para a pasta 'manifests'
        working-directory: ./manifests
